require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "V1::Manager::Items", type: :request do
  MENU_ITEMS_SIZE = 5

  describe "GET #index" do
    before() do
      MENU_ITEMS_SIZE.times do |i|
        create(:item_with_category, price: 5.99 + i, name: "Produto #{i+1}")
      end

      get "http://app.example.com/v1/manager/items"
    end

    it 'returns status code 200' do
      expect(response).to have_http_status(:success)
    end

    it 'should return all the menu itens' do
      expect(JSON.parse(response.body).size).to eq(MENU_ITEMS_SIZE)
    end
  end
end
