require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "V1::Manager::Items", type: :request do
  MENU_ITEMS_SIZE = 5

  describe "GET #index" do
    before() do
      MENU_ITEMS_SIZE.times do |i|
        create(:item_with_category, price: 5.99 + i, name: "Produto #{i+1}")
      end

      get "http://app.example.com/v1/manager/items"
    end

    it 'returns status code 200' do
      expect(response).to have_http_status(:success)
    end

    it 'should return all the menu itens' do
      expect(JSON.parse(response.body).size).to eq(MENU_ITEMS_SIZE)
    end
  end

  describe "GET #show" do
    before() do
      @item = create(:item_with_category, price: 5.99, name: "Litrão Skol")

      get "http://app.example.com/v1/manager/items/#{@item.id}"
    end

    it 'returns status code 200' do
      expect(response).to have_http_status(:success)
    end

    it 'should return the menu item requeted' do
      expect(JSON.parse(response.body)['id']).to eq(@item.id)
      expect(JSON.parse(response.body)['name']).to eq(@item.name)
    end
  end

  describe "GET #create" do
    before() do
      item_params = {item: {name: "Cerveja 600ml", price: 5.90, available: true, quantity: 10}}
      @item_count = Item.count
      post "http://app.example.com/v1/manager/items/", params: item_params
    end

    it 'returns status code created' do
      expect(response).to have_http_status(:created)
    end

    it 'should return the menu item created' do
      expect(JSON.parse(response.body)['name']).to eq('Cerveja 600ml')
      expect(JSON.parse(response.body)['price']).to eq(5.90)
    end

    it 'should create an item in the DB' do
      expect(Item.count).to eq @item_count + 1
    end
  end
end
