require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/v1/manager/bills", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Bill. As you add validations to Bill, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    {bill: {user_id: create(:user).id, table_id: create(:table).id, final_bill: 9.9}}
  }

  let(:invalid_attributes) {
    {bill: {final_bill: nil}}
  }

  # This should return the minimal set of values that should be in the headers
  # in order to pass any filters (e.g. authentication) defined in
  # BillsController, or in your router and rack
  # middleware. Be sure to keep this updated too.
  let(:valid_headers) {
    @user_app = User.find_by(email: "app@admin.com")
    headers = @user_app.create_new_auth_token
    headers["Subdomain"] = 'app'
    headers
  }

  let(:unauthorized_headers) {
    @user_unauthorized = create(:user)
    headers = @user_unauthorized.create_new_auth_token
    headers["Subdomain"] = 'app'
    headers
  }

  BILLS_SIZE = 3

  describe "GET #index" do
    context "with permissions" do
      before do
        BILLS_SIZE.times do |i|
          create(:bill)
        end
        get "http://app.example.com/v1/manager/bills", params: {}, headers: valid_headers
      end

      it 'returns status code 200' do
        expect(response).to have_http_status(:success)
      end

      it 'should return all the restaurant bills' do
        expect(JSON.parse(response.body).size).to eq(BILLS_SIZE)
      end
    end
  end

  describe "GET #show" do
    context "with permissions" do
      before do
        @bill = create(:bill)

        get "http://app.example.com/v1/manager/bills/#{@bill.id}", params: {}, headers: valid_headers
      end

      it 'returns status code 200' do
        expect(response).to have_http_status(:success)
      end

      it 'should return the user restaurant' do
        expect(JSON.parse(response.body)['id']).to eq(@bill.id)
      end
    end

    context "without permissions" do
      before do
        @bill = create(:bill)

        get "http://app.example.com/v1/manager/bills/#{@bill.id}", params: {}, headers: unauthorized_headers
      end

      it 'returns status code unauthorized' do
        expect(response).to have_http_status(:unauthorized)
      end

      it 'should return an error message' do
        expect(JSON.parse(response.body)['error']).to eq('Apenas o dono do restaurante tem acesso à isso')
      end
    end
  end

  describe "POST #create" do
    context "with valid params" do
      before do
        @bills_count = Bill.count
        post "http://app.example.com/v1/manager/bills/", params: valid_attributes, headers: valid_headers
      end

      it 'returns status code created' do
        expect(response).to have_http_status(:created)
      end

      it 'should return the menu item created' do
        expect(JSON.parse(response.body)['final_bill']).to eq(9.9)
      end

      it 'should create an item in the DB' do
        expect(Bill.count).to eq @bills_count + 1
      end
    end

    context "with invalid params" do
      before do
        @bills_count = Bill.count
        post "http://app.example.com/v1/manager/bills/", params: invalid_attributes, headers: valid_headers
      end

      it 'returns status code unprocessable_entity' do
        expect(response).to have_http_status(:unprocessable_entity)
      end

      it 'should return an error message' do
        expect(JSON.parse(response.body)['final_bill'][0]).to eq('não pode ficar em branco')
      end

      it 'should not create an item in the DB' do
        expect(Bill.count).to eq @bills_count
      end
    end
  end

  describe "PUT #update" do
    context "with authorized user" do
      context "with valid params" do
        before do
          @bill = create(:bill)
          put "http://app.example.com/v1/manager/bills/#{@bill.id}", params: valid_attributes, headers: valid_headers
        end

        it 'returns status code updated' do
          expect(response).to have_http_status(200)
        end

        it 'should update the restaurant and show it' do
          expect(JSON.parse(response.body)['final_bill']).to eq(9.9)
        end
      end

      context "with invalid params" do
        before do
          @bill = create(:bill)
          @bills_count = Bill.count
          put "http://app.example.com/v1/manager/bills/#{@bill.id}", params: invalid_attributes, headers: valid_headers
        end

        it 'returns status code unprocessable_entity' do
          expect(response).to have_http_status(:unprocessable_entity)
        end

        it 'should return an error message' do
          expect(JSON.parse(response.body)['final_bill'][0]).to eq('não pode ficar em branco')
        end

        it 'should not create an item in the DB' do
          expect(Bill.count).to eq @bills_count
        end

      end
    end

    context "with unauthorized user" do
      before do
        @bill = create(:bill)
        put "http://app.example.com/v1/manager/bills/#{@bill.id}", params: valid_attributes, headers: unauthorized_headers
      end

      it 'returns status code unauthorized' do
        expect(response).to have_http_status(:unauthorized)
      end

      it 'should return an error message' do
        expect(JSON.parse(response.body)['error']).to eq('Apenas o dono do restaurante tem acesso à isso')
      end

    end
  end

  describe "DELETE #destroy" do
    context "with user authorized" do
      before do
        @bill = create(:bill)
        @bills_count = Bill.count
        delete "http://app.example.com/v1/manager/bills/#{@bill.id}", params: {}, headers: valid_headers
      end

      it 'returns status code deleted' do
        expect(response).to have_http_status(204)
      end

      it 'should delete the item' do
        expect(Bill.count).to eq @bills_count - 1
      end
    end

    context "with user unauthorized" do
      before do
        @bill = create(:bill)
        @bills_count = Bill.count
        delete "http://app.example.com/v1/manager/bills/#{@bill.id}", params: {}, headers: unauthorized_headers
      end

      it 'returns status code unauthorized' do
        expect(response).to have_http_status(:unauthorized)
      end

      it 'should not delete the item' do
        expect(Bill.count).to eq @bills_count
      end
    end

  end
end
