development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: redis://redistogo:a39f47798a8593f4c7b3a484cfa21751@hammerjaw.redistogo.com:9107/
  channel_prefix: KelneroApi_production
